### ISSUE TITLE
Danger Warn vs Danger Fail

### ISSUE THREAD

**Issue by audiolion** [withspectrum/danger-plugin-no-console#5]
Is there a way to make it so a warning is produced about the console.logs instead of a failure?

**Comment by mxstbr** [comment]
PR welcome adding an option to switch that!

**Comment by patrickkempff** [comment]
Hey @audiolion! PR #20 fixes this. It allows you to pass a custom callback.

// edit
@mxstbr It would be awesome if you can publish an new version on npm! 👍

**Comment by audiolion** [comment]
@patrickkempff nice man! thanks so much
